# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('takeout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('number', models.PositiveIntegerField(verbose_name='电话号码')),
                ('text', models.TextField(max_length=30, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.Food')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '评论',
                'verbose_name_plural': '全部评论',
            },
        ),
    ]
