# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, verbose_name='位置')),
                ('image', models.CharField(max_length=500, verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '轮播图(五张)',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜名')),
                ('price', models.CharField(max_length=10, verbose_name='单价')),
                ('time', models.DateTimeField(verbose_name='创建时间')),
                ('image', models.CharField(max_length=500, verbose_name='图片地址')),
                ('introduce', models.TextField(blank=True, max_length=100, verbose_name='介绍')),
                ('isright', models.BooleanField(default=False, verbose_name='是否推到首页')),
            ],
            options={
                'ordering': ['-time'],
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='secondMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='菜系名')),
                ('image', models.CharField(max_length=100, verbose_name='dock图')),
            ],
            options={
                'verbose_name': '二级菜系',
                'verbose_name_plural': '二级菜系',
            },
        ),
        migrations.CreateModel(
            name='topMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='菜系名')),
            ],
            options={
                'verbose_name': '顶级菜系(仅修改)',
                'verbose_name_plural': '顶级菜系',
            },
        ),
        migrations.AddField(
            model_name='secondmenu',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.topMenu'),
        ),
        migrations.AddField(
            model_name='food',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takeout.secondMenu'),
        ),
    ]
