# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(max_length=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='secondmenu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='菜系名'),
        ),
        migrations.AlterField(
            model_name='topmenu',
            name='name',
            field=models.CharField(max_length=50, verbose_name='菜系名'),
        ),
    ]
