# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeout', '0002_auto_20170906_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name='单价'),
        ),
    ]
