# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170905_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, max_length=11, verbose_name='电话号码'),
        ),
    ]
