# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170906_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.IntegerField(verbose_name='电话号码'),
        ),
    ]
